name: plaid-bridges
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.11
##### DEV #####
  - hdf5
  - vtk>=9.4
  - pycgns-core
  - muscat-core=2.5
  - pip
  - pip:
##### RUN #####
    - torch
    - torch-geometric
    - pyplaid==0.1.8
##### DEV #####
    - plaid-ops==0.1.8
#---# testing
    - pytest
    - pytest-cov
#---# code formatters
    - ruff
    - pyright[nodejs]
#---# dev
    - pre-commit
#---# doc
    - sphinx
    - sphinx-autoapi
    - myst-nb
    - myst-parser
    - jupytext
    - furo
