name: plaid-bridges
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.11
##### DEV #####
  - hdf5
  - vtk>=9.4
  - pycgns-core
  - muscat-core=2.5
  - pip
  - pip:
##### RUN #####
    - torch
    - torch-geometric
    - git+https://github.com/PLAID-lib/plaid.git
##### DEV #####
    - git+https://github.com/PLAID-lib/plaid-ops.git@0c03a615dcd34fcc0d02b7067a065506b25df4ec
#---# testing
    - pytest
    - pytest-cov
#---# code formatters
    - ruff
    - pyright[nodejs]
#---# dev
    - pre-commit
#---# doc
    - sphinx
    - sphinx-autoapi
    - myst-nb
    - myst-parser
    - jupytext
    - furo
