name: plaid-bridges
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
##### RUN #####
  - pip
  - pip:
    - h5py
    - pyplaid==0.1.7
    - torch
    - torch-geometric
##### DEV #####
    - pre-commit
    - ruff
    - pyright[nodejs]
    - pytest
    - sphinx
    - sphinx-autoapi
    - myst-nb
    - furo