name: plaid-bridges
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
##### RUN #####
#---# plaid
  - plaid=0.1.6
  - muscat=2.4.1
#---# pip dependencies
  - pip
  - pip:
    - pre-commit
    - ruff
    - pyright[nodejs]
    - pytest
    - torch
    - torch-geometric
    - sphinx
    - sphinx-autoapi
    - myst-nb
    - furo
