name: Documentation

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC

permissions:
  contents: read

jobs:
  doc:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    env:
      # Conda configuration
      CONDA_PKGS_DIRS: ${{ github.workspace }}/conda_pkgs_dir
      CONDA_ENVS_PATH: ${{ github.workspace }}/conda_envs
      # Pip cache
      PIP_CACHE_DIR: ${{ github.workspace }}/.pip_cache
      # Temporary directories
      TMPDIR: ${{ github.workspace }}/tmp
      TEMP: ${{ github.workspace }}/tmp
      TMP: ${{ github.workspace }}/tmp
      # Hugging Face cache
      HF_HOME: ${{ github.workspace }}/hf_home

    steps:
      - name: Install free (procps)
        run: sudo apt-get update && sudo apt-get install -y procps

      - name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          remove-android: 'true'        # +10 GB
          remove-dotnet: 'true'         # +3 GB
          remove-haskell: 'true'        # +2 GB
          remove-docker-images: 'true'  # +3 GB

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install VC++ runtime (Windows only)
        if: runner.os == 'Windows'
        run: choco install vcredist2017 -y

      - name: Install Miniconda manually in workspace
        run: |
          mkdir -p $GITHUB_WORKSPACE/tmp
          curl -sL https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -o miniforge.sh
          bash miniforge.sh -b -p $GITHUB_WORKSPACE/miniconda3
          echo "$GITHUB_WORKSPACE/miniconda3/bin" >> $GITHUB_PATH

      - name: Create environment
        run: |
          conda env create -n plaid-bridges -f environment.yml
          conda run -n plaid-bridges python -m pip install -e .[dev]

      - name: Compile documentation
        run: |
          cd docs
          conda run -n plaid-bridges bash generate_doc.sh