name: Tests

permissions:
  contents: read

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install library
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests on Linux
        if: runner.os == 'Linux'
        run: |
          echo $GITHUB_REPOSITORY
          pytest tests --cov=src --cov-report=xml --cov-report=term

      - name: Run tests on macOS
        if: runner.os == 'macOS'
        run: |
          pytest tests

      - name: Run tests on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          pytest tests

      - name: Upload coverage to Codecov (Linux and python 3.11 only)
        if: runner.os == 'Linux' && matrix.python-version == '3.11'
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: PLAID-lib/plaid-bridges
          name: python-${{ matrix.python-version }}
          verbose: true